//
// MarketPlaceException.h
//
// $Id: /MarketPlaceServer/include/MarketPlaceException.h#1 $
//
// Definition of the MarketPlaceException class.
//
// Copyright (c) 2014, Choice Net Project
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//


#ifndef MarketPlaceException_INCLUDED
#define MarketPlaceException_INCLUDED


#include <Poco/Exception.h>
#include <typeinfo>
#include <string>

namespace ChoiceNet
{
namespace Eco
{


class MarketPlaceException: public Poco::Exception
	/// Base class for all Market Place Exceptions
{
public:
	MarketPlaceException(const std::string& msg, int code = 0);
		/// Creates MarketPlace Exception.

	MarketPlaceException(const MarketPlaceException& exc);
		/// Creates Market Place Exception.

	~MarketPlaceException() throw();
		/// Destroys Market Place Exception.

	MarketPlaceException& operator=(const MarketPlaceException& exc);
		/// Assignment operator.

	const char* name() const throw();
		/// Returns exception name.

	const char* className() const throw();
		/// Returns the name of the exception class.

	Poco::Exception* clone() const;
		/// Creates an exact copy of the exception.
		///
		/// The copy can later be thrown again by
		/// invoking rethrow() on it.

	void rethrow() const;
		/// (Re)Throws the exception.
		///
		/// This is useful for temporarily storing a
		/// copy of an exception (see clone()), then
		/// throwing it again.
};


//
// inlines
//
inline MarketPlaceException& MarketPlaceException::operator=(const MarketPlaceException& exc)
{
	Poco::Exception::operator=(exc);
	return *this;
}


inline const char* MarketPlaceException::name() const throw()
{
	return "Market Place Server";
}


inline const char* MarketPlaceException::className() const throw()
{
	return typeid(*this).name();
}


inline Poco::Exception* MarketPlaceException::clone() const
{
	return new MarketPlaceException(*this);
}


inline void MarketPlaceException::rethrow() const
{
	throw *this;
}


} } // namespace ChoiceNet::Eco


#endif // MarketPlaceException_INCLUDED
